export const TournamentsData = [
    {
        name:'tour1',
        url_for_banner:'https://res.cloudinary.com/dk88eyahu/image/upload/v1606327391/useTeam/tournament1_r2lflx.png',
        url_for_card:'https://res.cloudinary.com/dk88eyahu/image/upload/v1606327391/useTeam/tournament1_r2lflx.png',
        description: 'Its your way to become Dota 2 pro-player1',
        status:'announce',
        mode:'5*5',
        entry_from:'20',
        entry_pool:'Real money',
        prise_pool:'Real money',
        prise_sum:'2000',
        slots:'4',
        server:'EU',
        start_date:'01/01/2021',
        start_time:"8:30 p.m.",
        info:'bla bla bla',
        winners:[],
    },
    {
        name:'tour2',
        url_for_banner:'https://res.cloudinary.com/dk88eyahu/image/upload/v1606327396/useTeam/tournament2_rntabh.png',
        url_for_card:'https://res.cloudinary.com/dk88eyahu/image/upload/v1606327396/useTeam/tournament2_rntabh.png',
        description: 'Its your way to become Dota 2 pro-player2',
        status:'announce',
        mode:'1*1',
        entry_from:'20',
        entry_pool:'Energy',
        prise_pool:'Energy',
        prise_sum:'2000',
        slots:'32',
        server:'EU',
        start_date:'12/12/2020',
        start_time:"8:30 p.m.",
        info:'bla bla bla',
        winners:[],
    },
    {
        name:'tour3',
        url_for_banner:'https://res.cloudinary.com/dk88eyahu/image/upload/v1606398096/useTeam/banner-dota2_z64fyi.png',
        url_for_card:'https://res.cloudinary.com/dk88eyahu/image/upload/v1606398096/useTeam/banner-dota2_z64fyi.png',
        description: 'Its your way to become Dota 2 pro-player3',
        status:'announce',
        mode:'5*5',
        entry_from:'20',
        entry_pool:'Energy',
        prise_pool:'Energy',
        prise_sum:'2000',
        slots:'16',
        server:'USA',
        start_date:'12/12/2020',
        start_time:"8:30 p.m.",
        info:'bla bla bla',
        winners:[],
    },
    {
        name:'tour4',
        url_for_banner:'https://res.cloudinary.com/dk88eyahu/image/upload/v1606398101/useTeam/kunkkabloodseeker_s1bzdh.jpg',
        url_for_card:'https://res.cloudinary.com/dk88eyahu/image/upload/v1606398101/useTeam/kunkkabloodseeker_s1bzdh.jpg',
        description: 'Its your way to become Dota 2 pro-player3',
        status:'common',
        mode:'1*1',
        entry_from:'200',
        entry_pool:'Real money',
        prise_pool:'Real money',
        prise_sum:'5000',
        slots:'32',
        server:'EU',
        start_date:'15/02/2021',
        start_time:"8:30 p.m.",
        info:'bla bla bla',
        winners:[],
    },
    {
        name:'tour5',
        url_for_banner:'https://res.cloudinary.com/dk88eyahu/image/upload/v1606398275/useTeam/FYz_jIXNVZWCd6fDqDIRnmotJ5WCoZ-opw1FDdnxrEY_po6tao.png',
        url_for_card:'https://res.cloudinary.com/dk88eyahu/image/upload/v1606418730/useTeam/FYz_jIXNVZWCd6fDqDIRnmotJ5WCoZ-opw1FDdnxrEY_po6tao.png',
        description: 'Its your way to become Dota 2 pro-player3',
        status:'current',
        mode:'1*1',
        entry_from:'20',
        entry_pool:'Energy',
        prise_pool:'Energy',
        prise_sum:'2000',
        slots:'32',
        server:'EU',
        start_date:'11/12/2020',
        start_time:"8:30 p.m.",
        info:'bla bla bla',
        winners:[],
    },
    {
        name:'tour6',
        url_for_banner:'https://res.cloudinary.com/dk88eyahu/image/upload/v1606398096/useTeam/dota-2-banner-2_dweulm.jpg',
        url_for_card:'https://res.cloudinary.com/dk88eyahu/image/upload/v1606398096/useTeam/dota-2-banner-2_dweulm.jpg',
        description: 'Its your way to become Dota 2 pro-player3',
        status:'current',
        mode:'1*1',
        entry_from:'20',
        entry_pool:'Energy',
        prise_pool:'Energy',
        prise_sum:'2000',
        slots:'32',
        server:'EU',
        start_date:'12/12/2020',
        start_time:"8:30 p.m.",
        info:'bla bla bla',
        winners:[],
    },
    {
        name:'tour7',
        url_for_banner:'https://res.cloudinary.com/dk88eyahu/image/upload/v1606398099/useTeam/dota2-banner_oug7re.jpg',
        url_for_card:'https://res.cloudinary.com/dk88eyahu/image/upload/v1606398099/useTeam/dota2-banner_oug7re.jpg',
        description: 'Its your way to become Dota 2 pro-player3',
        status:'current',
        mode:'1*1',
        entry_from:'20',
        entry_pool:'Energy',
        prise_pool:'Energy',
        prise_sum:'2000',
        slots:'32',
        server:'EU',
        start_date:'12/12/2020',
        start_time:"8:30 p.m.",
        info:'bla bla bla',
        winners:[],
    },
    {
        name:'tour7',
        url_for_banner:'https://res.cloudinary.com/dk88eyahu/image/upload/v1606398099/useTeam/dota2-banner_oug7re.jpg',
        url_for_card:'https://res.cloudinary.com/dk88eyahu/image/upload/v1606398099/useTeam/dota2-banner_oug7re.jpg',
        description: 'Its your way to become Dota 2 pro-player3',
        status:'archive',
        mode:'1*1',
        entry_from:'20',
        entry_pool:'Energy',
        prise_pool:'Energy',
        prise_sum:'2000',
        slots:'32',
        server:'EU',
        start_date:'12/12/2020',
        start_time:"8:30 p.m.",
        info:'bla bla bla',
        winners:[],
    }

]